- name: Update
  hosts: '{{ group }}'
  remote_user: jagabluat
  become: yes
  tasks:
  - name: Update cache
    ansible.builtin.apt:
      update_cache: yes
  - name: Upgrade
    ansible.builtin.apt:
      upgrade: full # full upgrade is recommended for Raspberry Pi OS: https://www.raspberrypi.com/documentation/computers/os.html#install-updates
